In [1]:
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
def ReadData():
    # 读取数据
    temp = pd.read_excel("lab3data.xlsx")   # 通过pandas中的read_excel方法读取xlsx表格文件
    print("数据读取如下形式：")
    print(temp)
    return temp

In [4]:
def DataProcess(data_pre):
    # 数据处理 返回各个类别的样本点的数据
    data_3=data_pre[data_pre['class']==3]  #筛选对应类别为3的样本数据
    data_4=data_pre[data_pre['class']==4]  #筛选对应类别为4的样本数据
    x31=data_3['dim1'].values    # class=3 x1
    x32=data_3['dim2'].values    # class=3 x2
    x41=data_4['dim1'].values    # class=4 x1
    x42=data_4['dim2'].values    # class=4 x2
    return data_3x31,x32,x41,x42

In [5]:
def HighDimMapping(x1, x2):
    # 将数据向高维映射
    data_ret = []
    # 10个样本点
    for i in range(10):
        temparr = []
        temparr.append(1.0)
        temparr.append(x1[i])
        temparr.append(x2[i])
        temparr.append(x1[i]**2)
        temparr.append(x1[i]* x2[i])
        temparr.append(x2[i]**2)
        data_ret.append(temparr)
    return np.array(data_ret)

In [7]:
data = ReadData()

数据读取如下形式：
    dim1  dim2  class
0   -3.0  -2.9      3
1    0.5   8.7      3
2    2.9   2.1      3
3   -0.1   5.2      3
4   -4.0   2.2      3
5   -1.3   3.7      3
6   -3.4   6.2      3
7   -4.1   3.4      3
8   -5.1   1.6      3
9    1.9   5.1      3
10  -2.0  -8.4      4
11  -8.9   0.2      4
12  -4.2  -7.7      4
13  -8.5  -3.2      4
14  -6.7  -4.0      4
15  -0.5  -9.2      4
16  -5.3  -6.7      4
17  -8.7  -6.4      4
18  -7.1  -9.7      4
19  -8.0  -6.3      4


In [8]:
x31,x32,x41,x42 = DataProcess(data)  # 数据筛选清洗

In [9]:
feature3 = HighDimMapping(x31,x32)
feature4 = HighDimMapping(x41,x42)
feature = np.concatenate((feature3,feature4),axis=0)

In [10]:
clf = SVC(C=0.3,kernel='linear')   # 调用SKlearn中的支持向量机分类器
labels = np.array([3]*10 + [4]*10)  # 规格化标签

In [11]:
clf.fit(feature,labels)

SVC(C=0.3, kernel='linear')

In [12]:
print("---- 支持向量的索引值 ----")
print(clf.support_)
print('---- 支持向量 ----')
print(clf.support_vectors_)
print('----- 决策函数decision function特征系数参数 -----')
print(clf.coef_)
print('----- 决策函数常量参数（截距） ----')
print(clf.intercept_)
print('---- 支持向量数 ----')
print(clf.n_support_)

---- 支持向量的索引值 ----
[ 0  1 10 11 15]
---- 支持向量 ----
[[ 1.000e+00 -3.000e+00 -2.900e+00  9.000e+00  8.700e+00  8.410e+00]
 [ 1.000e+00  5.000e-01  8.700e+00  2.500e-01  4.350e+00  7.569e+01]
 [ 1.000e+00 -2.000e+00 -8.400e+00  4.000e+00  1.680e+01  7.056e+01]
 [ 1.000e+00 -8.900e+00  2.000e-01  7.921e+01 -1.780e+00  4.000e-02]
 [ 1.000e+00 -5.000e-01 -9.200e+00  2.500e-01  4.600e+00  8.464e+01]]
----- 决策函数decision function特征系数参数 -----
[[-1.30104261e-18 -1.11120406e-02 -9.88635351e-02  3.78999287e-02
   2.10449994e-02  2.39074147e-02]]
----- 决策函数常量参数（截距） ----
[-2.04490349]
---- 支持向量数 ----
[2 3]


In [13]:
x = np.array([0, 10])
y = -1/clf.coef_[0,1] * (clf.coef_[0,0] * x + clf.intercept_)

In [14]:
plt.scatter(data_3['dim1'], data_3['dim2'], c='red')
plt.scatter(data_4['dim1'], data_4['dim2'], c='blue')
plt.plot(x,y)
plt.show()

NameError: name 'data_3' is not defined